server:
  port: 8082
spring:
  application:
    name: ACCOUNTSERVICE
  h2:
    console:
      enabled: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
